use utoipa::OpenApi;

use crate::dto::{
    ClientDto, ClientsResponse, CreateSessionRequest, CreateSessionResponse, ErrorResponse,
    FlowDto, FlowInspectResponse, FlowsResponse, HealthResponse, HistoryEntryDto, HistoryResponse,
    MessageDebugDto, MessageRequest, MessageResponse, OverviewResponse, PlatformConfigResponse,
    PlatformStatusResponse, PromptIdentityDto, PromptSetDetailDto, PromptSetDto, PromptSetsResponse,
    PromptTemplateDto, ReloadResponse, SessionInspectResponse, SessionResponse,
};
use crate::dto::studio::{
    CreateProjectRequest, DraftFlowDto, FlowValidationResponse, ProjectAssetsResponse,
    ProjectStatusResponse, PublishResponse, StudioProjectDetailResponse, StudioProjectsResponse,
    UpdateProjectRequest, VersionsResponse,
};
use crate::handlers;

#[derive(OpenApi)]
#[openapi(
    paths(
        handlers::health::health,
        handlers::flows::list_flows,
        handlers::clients::list_clients,
        handlers::clients::get_client,
        handlers::overview::overview,
        handlers::overview::platform_status,
        handlers::overview::platform_config,
        handlers::session::create_session,
        handlers::session::get_session,
        handlers::session::delete_session,
        handlers::inspect::inspect_session,
        handlers::inspect::inspect_flow,
        handlers::message::send_message,
        handlers::history::get_history,
        handlers::prompt::list_prompt_sets,
        handlers::prompt::get_prompt_set,
        handlers::prompt::reload_prompts,
        handlers::studio::list_projects,
        handlers::studio::create_project,
        handlers::studio::get_project,
        handlers::studio::update_project,
        handlers::studio::delete_project,
        handlers::studio::get_project_status,
        handlers::studio::get_project_assets,
        handlers::studio::publish_project,
        handlers::studio::validate_flow_handler,
        handlers::studio::reload_flows,
    ),
    components(schemas(
        HealthResponse,
        FlowDto,
        FlowsResponse,
        ClientDto,
        ClientsResponse,
        CreateSessionRequest,
        CreateSessionResponse,
        SessionResponse,
        SessionInspectResponse,
        FlowInspectResponse,
        MessageRequest,
        MessageResponse,
        MessageDebugDto,
        HistoryResponse,
        HistoryEntryDto,
        PromptSetsResponse,
        PromptSetDto,
        PromptSetDetailDto,
        PromptIdentityDto,
        PromptTemplateDto,
        ReloadResponse,
        OverviewResponse,
        PlatformStatusResponse,
        PlatformConfigResponse,
        StudioProjectsResponse,
        StudioProjectDetailResponse,
        CreateProjectRequest,
        UpdateProjectRequest,
        ProjectStatusResponse,
        ProjectAssetsResponse,
        DraftFlowDto,
        FlowValidationResponse,
        PublishResponse,
        VersionsResponse,
        ErrorResponse,
        crate::errors::ApiErrorCode,
        crate::dto::RuntimeStateDto,
    )),
    tags(
        (name = "health", description = "Health checks"),
        (name = "flows", description = "Flow registry"),
        (name = "clients", description = "Client data files"),
        (name = "sessions", description = "Session lifecycle"),
        (name = "messages", description = "User messages"),
        (name = "history", description = "Conversation history"),
        (name = "prompts", description = "Prompt set management"),
        (name = "studio", description = "AI Studio authoring API"),
        (name = "platform", description = "Platform monitoring"),
    ),
    info(
        title = "AI Flow API",
        version = "0.1.0",
        description = "HTTP API for AI Flow Runtime and AI Platform"
    )
)]
pub struct ApiDoc;
